sudo: false
language: node_js
node_js:
  - "10"
before_install:
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm run lint:spec
  - npm run test
after_success:
  - npm run coverage
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: develop
    local_dir: coverage
    email: aqua.hong.97@gmail.com
    name: Hongarc's bot
