version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-node-v10
      - test-node-v11

jobs:
  test-node-v10: &test-template
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests error code
      - run: yarn lint
  test-node-v11:
    <<: *test-template
    docker:
      - image: circleci/node:11
